# Generated by Django 4.2.27 on 2026-01-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forecaster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="daily_capacity",
            field=models.IntegerField(default=8, help_text="Available hours per day"),
        ),
        migrations.CreateModel(
            name="EmployeeMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_type", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                ("date_recorded", models.DateField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="forecaster.teammember",
                    ),
                ),
            ],
        ),
    ]
