# Generated by Django 4.2.27 on 2026-01-10 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("forecaster", "0003_taskstatuslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatuslog",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
